---
- name: Setup Editors
  hosts: all
  become: yes
  become_method: sudo
  tasks:
   - name: nano remove
     apt: name=nano state=absent
   - name: vim install
     apt: name=vim state=present
   - name: emacs install
     apt: name=emacs state=present



